version: "3.8"

services:
  selenium:
    container_name: browser
    image: "selenium/standalone-chrome"
    shm_size: "500mb"
    restart: on-failure
    cpus: '0.5'
    mem_limit: 750M
    environment:
      VNC_NO_PASSWORD: 1
      SE_NODE_SESSION_TIMEOUT: 999999999
    networks:
      - web
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4444/wd/hub/status"]
      interval: 10s
      timeout: 5s
      retries: 10

  instagram-bot:
    container_name: instabot
    read_only: true
    build: .
    env_file: .env
    restart: on-failure
    cpus: '0.5'
    mem_limit: 1000M
    links:
      - "selenium:selenium"
    depends_on:
      - selenium
    networks:
      - web

networks:
  web:
    name: instabot_web
