version: "3.9"
services:
  selenium:
    image: "selenium/standalone-chrome"
    environment:
      VNC_NO_PASSWORD: 1
      SE_NODE_SESSION_TIMEOUT: 999999999
    #ports:             # Access in browser at ip:4444, only use for troubleshooting.
    # - "4444:4444"     # NOT AUTHENTICATED, anyone can access/control your Instagram if this is enabled.
    shm_size: 2gb
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4444/wd/hub/status"]
      interval: 10s
      timeout: 5s
      retries: 3
    restart: unless-stopped
  instagram-bot:
    build: .
    links:
      - "selenium:selenium"
    depends_on:
      - selenium
    restart: no